option '-n', '--name [NAME]', 'name you want to greet'
task "greet", "Say hi to the nice people", (options)->
  message = "Hello, "
  if options.name?
    message += options.name
  else
    message += "World"
  console.log message

task "clean", "Clean up build directories", ->
  console.log "cleaning up..."

task "build", "Build the project files", ->
  console.log "building..."